//  GatewayResponse.swift
//  CommandGuard
//
/*
This file was developed with the assistance of the generative AI tool ChatGPT. All pieces of this file have been assisted by AI.
All AI-generated content was reviewed for understanding and cleanliness, tested for correctness and expected results,
and verified by Luke Arsenault.
*/
//  Models the response payload returned by the gateway.

import Foundation

// Delivery status reported by the gateway (transport-level delivery outcome).
enum DeliveryStatus: String, Codable {
    case delivered
    case failed
}

// Execution status reported by the gateway (app-level success/failure).
enum ExecutionStatus: String, Codable {
    case succeeded
    case failed
}

// Codable response envelope expected from the gateway over NDJSON.
struct GatewayResponse: Codable {
    // Request identifier echoed back for correlation.
    let id: Int
    // Delivery status for the request.
    let deliveryStatus: DeliveryStatus
    // Execution status for the command.
    let executionStatus: ExecutionStatus
    // Optional message describing success/failure details.
    let message: String?
    // ISO-8601 timestamp generated by the gateway.
    let timestamp: String
}
