//  CommandModels.swift
//  CommandGuard
//
/*
This file was developed with the assistance of the generative AI tool ChatGPT. All pieces of this file have been assisted by AI.
All AI-generated content was reviewed for understanding and cleanliness, tested for correctness and expected results,
and verified by Luke Arsenault.
*/

//  Shared command models and helpers for building/sending/receiving control commands.

import Foundation

// Distinguishes normal operator commands from adversarial test/emulation payloads.
public enum CommandIntent: String, Codable {
    case operational
    case enemyEmulation
}

// Compact operational command used for standard equipment control actions.
public struct OperationalCommandBody: Codable {
    // Requested fan output in percent (0...100).
    public let fanSpeedPercent: Double
    // Requested valve opening in percent (0...100).
    public let valvePositionPercent: Double
    // Equipment master power state requested by the sender.
    public let equipmentPower: Bool
    // Explicitly toggles enemy emulation mode in operational payloads.
    public let enemyEmulation: Bool

    // Memberwise initializer for operational command payload values.
    public init(
        fanSpeedPercent: Double,
        valvePositionPercent: Double,
        equipmentPower: Bool,
        enemyEmulation: Bool
    ) {
        self.fanSpeedPercent = fanSpeedPercent
        self.valvePositionPercent = valvePositionPercent
        self.equipmentPower = equipmentPower
        self.enemyEmulation = enemyEmulation
    }
}

// Expanded command used for enemy-emulation scenarios with setpoint manipulation.
public struct EnemyCommandBody: Codable {
    // Target temperature setpoint in Fahrenheit.
    public let temperatureSetpointF: Double
    // Target humidity setpoint in relative humidity percent.
    public let humiditySetpointPercent: Double
    // Requested fan output in percent.
    public let fanSpeedPercent: Double
    // Requested valve opening in percent.
    public let valvePositionPercent: Double
    // Equipment master power state requested by the sender.
    public let equipmentPower: Bool

    // Memberwise initializer for enemy-emulation command payload values.
    public init(
        temperatureSetpointF: Double,
        humiditySetpointPercent: Double,
        fanSpeedPercent: Double,
        valvePositionPercent: Double,
        equipmentPower: Bool
    ) {
        self.temperatureSetpointF = temperatureSetpointF
        self.humiditySetpointPercent = humiditySetpointPercent
        self.fanSpeedPercent = fanSpeedPercent
        self.valvePositionPercent = valvePositionPercent
        self.equipmentPower = equipmentPower
    }
}

// Generic envelope used for typed command bodies while sharing common metadata/signature fields.
public struct TypedCommandEnvelope<Body: Codable>: Codable {
    // ISO 8601 UTC timestamp string supplied by the sender.
    public let timestamp: String
    // Monotonic request identifier generated by the client.
    public let requestId: Int
    // Logical operator identity attributed to the command.
    public let operatorId: String
    // Base64 nonce used to detect replay.
    public let nonce: String
    // Declares whether this envelope is operational or enemy-emulation.
    public let intent: CommandIntent
    // Typed command payload body.
    public let command: Body
    // Optional detached signature metadata/value for verification.
    public var signature: Signature?

    // Build a typed envelope; `signature` remains nil until signing is performed.
    public init(
        timestamp: String,
        requestId: Int,
        operatorId: String,
        nonce: String,
        intent: CommandIntent,
        command: Body,
        signature: Signature? = nil
    ) {
        self.timestamp = timestamp
        self.requestId = requestId
        self.operatorId = operatorId
        self.nonce = nonce
        self.intent = intent
        self.command = command
        self.signature = signature
    }
}


// Helper: current time in ISO 8601 (UTC, fractional seconds).
public func iso8601Now() -> String {
    let formatter = ISO8601DateFormatter()
    formatter.timeZone = TimeZone(secondsFromGMT: 0)
    formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
    return formatter.string(from: Date())
}

// Helper: cryptographically secure random nonce (Base64), default 16 bytes.
public func makeNonceBase64(byteCount: Int = 16) -> String {
    var bytes = [UInt8](repeating: 0, count: byteCount) // Build a 16 byte array of 0's initially
    let status = SecRandomCopyBytes(kSecRandomDefault, byteCount, &bytes) // Put 16 random numbers in place of the 0's from before. If succeeded mark true or false is fail
    precondition(status == errSecSuccess, "Failed to generate nonce") // Check the status of from before and if success, continue. Else, give error message
    return Data(bytes).base64EncodedString() // Return the 16 byte array as a 16 digit nonce base64 encoded
}

// Canonical JSON encoder for typed envelopes; excludes signature and sorts keys deterministically.
public func encodeCanonicalEnvelope<Body: Codable>(_ envelope: TypedCommandEnvelope<Body>) throws -> Data {
    var copy = envelope // Work on a copy so caller data is untouched.
    copy.signature = nil // Signature is not part of the signed payload bytes.
    let encoder = JSONEncoder()
    encoder.outputFormatting = [.sortedKeys] // Keep byte output stable across runs.
    return try encoder.encode(copy) // Return canonical bytes for sign/verify.
}

// Signature info embedded in the envelope (Option A).
public struct Signature: Codable {
    public let alg: String  // ECDSA_P256_SHA256
    public let value: String  // Base64 encoded signature
    public let keyId: String  // Which key to verify with

    // Memberwise initializer.
    public init(alg: String, value: String, keyId: String) {
        self.alg = alg
        self.value = value
        self.keyId = keyId
    }
}

// Schema validation errors for command envelopes and stateful gateway checks.
public enum CommandSchemaError: LocalizedError {
    // JSON could not be parsed into the expected envelope model.
    case invalidJSON(reason: String)
    // Timestamp was missing or not valid ISO 8601 format.
    case invalidTimestampFormat
    // Timestamp did not strictly increase versus prior observed command.
    case timestampNotMonotonic
    // Timestamp spacing violated the minimum timing threshold.
    case timestampTooSoon
    // Request id was non-positive or malformed.
    case invalidRequestId
    // Request id did not match expected strict sequence.
    case requestIdOutOfSequence(expected: Int)
    // Operator id contained only whitespace or was empty.
    case emptyOperatorId
    // Operator id did not match the allowed identity.
    case operatorIdNotAllowed(expected: String)
    // Nonce was not valid Base64 content.
    case invalidNonce
    // Nonce matched an already accepted/recent value.
    case nonceReused
    // Temperature value violated allowed range.
    case temperatureOutOfRange(Double)
    // Humidity value violated allowed range.
    case humidityOutOfRange(Double)
    // Fan speed value violated percent range.
    case fanSpeedOutOfRange(Double)
    // Valve position value violated percent range.
    case valvePositionOutOfRange(Double)
    // Valve exceeded hard safety ceiling.
    case valvePositionUnsafe(Double)
    // Fan speed too low for a powered-on command.
    case fanSpeedTooLowForPower(Double)
    // Fan speed violated policy constraints for equipment mode.
    case fanSpeedPolicyViolation(Double)
    // Valve position violated policy constraints for equipment mode.
    case valvePositionPolicyViolation(Double)
    // Fan must be zero while power is off.
    case fanMustBeZeroWhenPowerOff(Double)
    // Valve must be zero while power is off.
    case valveMustBeZeroWhenPowerOff(Double)
    // Forward simulation predicted unsafe temperature before horizon end.
    case predictedTemperatureOutOfBounds(value: Double, horizonSeconds: Double)
    // Forward simulation predicted unsafe humidity before horizon end.
    case predictedHumidityOutOfBounds(value: Double, horizonSeconds: Double)
    // Signature object existed but required fields were blank.
    case invalidSignatureFields

    public var errorDescription: String? {
        switch self {
        case let .invalidJSON(reason):
            return "Invalid JSON: \(reason)"
        case .invalidTimestampFormat:
            return "Invalid timestamp format"
        case .timestampNotMonotonic:
            return "Timestamp is older than the last accepted value"
        case .timestampTooSoon:
            return "Timestamp is too close to current time"
        case .invalidRequestId:
            return "Invalid request id"
        case let .requestIdOutOfSequence(expected):
            return "Request id out of sequence (expected \(expected))"
        case .emptyOperatorId:
            return "Operator id is required"
        case let .operatorIdNotAllowed(expected):
            return "Operator id not allowed (expected \(expected))"
        case .invalidNonce:
            return "Nonce is not valid Base64"
        case .nonceReused:
            return "Nonce has already been used"
        case let .temperatureOutOfRange(value):
            return "Temperature out of range: \(value)"
        case let .humidityOutOfRange(value):
            return "Humidity out of range: \(value)"
        case let .fanSpeedOutOfRange(value):
            return "Fan speed out of range: \(value)"
        case let .valvePositionOutOfRange(value):
            return "Valve position out of range: \(value)"
        case let .valvePositionUnsafe(value):
            return "Valve position unsafe: \(value)"
        case let .fanSpeedTooLowForPower(value):
            return "Fan speed too low for power ON: \(value)"
        case let .fanSpeedPolicyViolation(value):
            return "Fan speed violates policy: \(value)"
        case let .valvePositionPolicyViolation(value):
            return "Valve position violates policy: \(value)"
        case let .fanMustBeZeroWhenPowerOff(value):
            return "Fan speed must be 0 when power is OFF: \(value)"
        case let .valveMustBeZeroWhenPowerOff(value):
            return "Valve position must be 0 when power is OFF: \(value)"
        case let .predictedTemperatureOutOfBounds(value, horizonSeconds):
            return "Predicted temperature out of bounds within \(Int(horizonSeconds))s: \(value)"
        case let .predictedHumidityOutOfBounds(value, horizonSeconds):
            return "Predicted humidity out of bounds within \(Int(horizonSeconds))s: \(value)"
        case .invalidSignatureFields:
            return "Signature fields are invalid"
        }
    }
}

// Stateless validation for JSON shape, ranges, and basic field constraints.
public enum CommandSchemaValidator {
    // Mirrors UI ranges and percent bounds to keep gateway validation consistent.
    private static let percentRange = 0.0...100.0

    public static func decodeAndValidateOperationalBasics(from data: Data) throws -> (TypedCommandEnvelope<OperationalCommandBody>, Date) {
        let decoder = JSONDecoder()
        do {
            // Decode typed operational envelope and validate metadata + body ranges.
            let envelope = try decoder.decode(TypedCommandEnvelope<OperationalCommandBody>.self, from: data)
            let timestamp = try validateEnvelopeBasics(envelope)
            try validateOperationalCommandBody(envelope.command)
            return (envelope, timestamp)
        } catch let error as CommandSchemaError {
            throw error
        } catch {
            throw CommandSchemaError.invalidJSON(reason: error.localizedDescription)
        }
    }

    public static func decodeAndValidateEnemyBasics(from data: Data) throws -> (TypedCommandEnvelope<EnemyCommandBody>, Date) {
        let decoder = JSONDecoder()
        do {
            // Decode typed enemy envelope and validate metadata + body ranges.
            let envelope = try decoder.decode(TypedCommandEnvelope<EnemyCommandBody>.self, from: data)
            let timestamp = try validateEnvelopeBasics(envelope)
            try validateEnemyCommandBody(envelope.command)
            return (envelope, timestamp)
        } catch let error as CommandSchemaError {
            throw error
        } catch {
            throw CommandSchemaError.invalidJSON(reason: error.localizedDescription)
        }
    }


    public static func validateEnvelopeBasics<Body>(_ envelope: TypedCommandEnvelope<Body>) throws -> Date {
        // Request id must be positive; sequence checks happen at gateway state layer.
        guard envelope.requestId > 0 else {
            throw CommandSchemaError.invalidRequestId
        }
        // Operator id cannot be blank after trimming whitespace.
        let trimmedOperatorId = envelope.operatorId.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedOperatorId.isEmpty else {
            throw CommandSchemaError.emptyOperatorId
        }
        // Parse timestamp format only; temporal monotonicity enforced separately.
        guard let timestamp = parseTimestamp(envelope.timestamp) else {
            throw CommandSchemaError.invalidTimestampFormat
        }
        // Nonce must be decodable from Base64.
        guard Data(base64Encoded: envelope.nonce) != nil else {
            throw CommandSchemaError.invalidNonce
        }
        // Signature presence is optional, but if present each field must be non-empty.
        if let signature = envelope.signature {
            if signature.alg.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ||
                signature.value.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ||
                signature.keyId.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                throw CommandSchemaError.invalidSignatureFields
            }
        }
        return timestamp
    }

    // Validates operational payload ranges used by typed operational envelopes.
    public static func validateOperationalCommandBody(_ command: OperationalCommandBody) throws {
        if !percentRange.contains(command.fanSpeedPercent) {
            throw CommandSchemaError.fanSpeedOutOfRange(command.fanSpeedPercent)
        }
        if !percentRange.contains(command.valvePositionPercent) {
            throw CommandSchemaError.valvePositionOutOfRange(command.valvePositionPercent)
        }
        if command.equipmentPower, command.fanSpeedPercent < 5 {
            throw CommandSchemaError.fanSpeedTooLowForPower(command.fanSpeedPercent)
        }
    }

    // Validates enemy-emulation payload fields.
    public static func validateEnemyCommandBody(_ command: EnemyCommandBody) throws {
        // Enemy emulation intentionally allows temperature/humidity to exceed normal ranges.
        guard
            command.temperatureSetpointF.isFinite,
            command.humiditySetpointPercent.isFinite
        else {
            throw CommandSchemaError.invalidJSON(reason: "Enemy command contains non-finite setpoint values")
        }
        // Actuator percentages remain bounded for fan/valve controls.
        if !percentRange.contains(command.fanSpeedPercent) {
            throw CommandSchemaError.fanSpeedOutOfRange(command.fanSpeedPercent)
        }
        if !percentRange.contains(command.valvePositionPercent) {
            throw CommandSchemaError.valvePositionOutOfRange(command.valvePositionPercent)
        }
    }

    public static func parseTimestamp(_ timestamp: String) -> Date? {
        // Accept fractional or non-fractional ISO 8601 timestamps.
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        if let date = formatter.date(from: timestamp) {
            return date
        }
        return ISO8601DateFormatter().date(from: timestamp)
    }
}
